name: build gatsby

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
  
      - name: Install dependencies
        run: npm install
  
      - name: Build
        run: npm build
        env:
          GH_API_KEY: ${{ secrets.ACCESS_TOKEN }}
          
      - name: deploy
      - uses: peaceiris/actions-gh-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GH_PAT: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
