name: Gatsby Publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: change node version
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: package install
        run: npm install
      
      - name: build gatsby
        run: npm build
        env:
          GH_API_KEY: ${{ secrets.ACCESS_TOKEN }}
      
      - name: CNAME copy
        run: cp CNAME public/
      
      - name : deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_PAT: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          BUILD_DIR: 'public/'
